__author__ = 'pascalpoizat'

from pyArduinoML.model.NamedElement import NamedElement


class App(NamedElement):
    """
    Application built over bricks.

    """

    def __init__(self, name, bricks=(), states=()):
        """
        Constructor.

        :param name: String, the name of the application
        :param bricks: List[Brick], bricks over which the application operates
        :param states: List[State], states of the application with the first one being the initial state
        :return:
        """
        NamedElement.__init__(self, name)
        self.bricks = bricks
        self.states = states

    def __repr__(self):
        """
        External representation: Arduino program

        :return: String
        """

        rtr = ""
        rtr += "// generated by ArduinoML\n"
        rtr += "\nvoid setup() {\n"
        rtr += "\n".join(map(lambda b: b.setup(), self.bricks))
        rtr += "\n}\n"
        if len(self.states) > 0:
            rtr += "\nvoid loop() { state_%s(); }\n" % self.states[0].name
        for state in self.states:
            rtr += "\nvoid state_%s() {\n" % state.name
            # generate code for state actions
            for action in state.actions:
                rtr += "\tdigitalWrite(%d, %s);\n" % (action.brick.pin, action.value)
            # generate code for the transition
            transition = state.transition
            rtr += "\tif (digitalRead(%d) == %s) { state_%s(); }\n" \
                   % (transition.sensor.pin, transition.value, transition.nextstate.name)
            # loop over state
            rtr += "\tstate_%s();" % state.name
            # end of state
            rtr += "\n};\n"
        # end
        return rtr
